# Generated by Django 5.2.6 on 2025-09-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasabiBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix_1', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix_2', models.CharField(blank=True, max_length=255, null=True)),
                ('last_backup_completed', models.BooleanField(default=False)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('successful_backups', models.PositiveIntegerField(default=0)),
                ('failed_backups', models.PositiveIntegerField(default=0)),
                ('total_files', models.PositiveBigIntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasabi_key', models.CharField(max_length=1024)),
                ('wasabi_key_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('etag', models.CharField(max_length=64)),
                ('last_modified', models.DateTimeField()),
                ('size', models.BigIntegerField()),
                ('local_path', models.CharField(max_length=1024)),
                ('local_etag', models.CharField(blank=True, max_length=64, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='purpleBackupApp.wasabibucket')),
            ],
            options={
                'unique_together': {('bucket', 'wasabi_key')},
            },
        ),
        migrations.CreateModel(
            name='BackupBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('successful_files', models.PositiveIntegerField(default=0)),
                ('failed_files', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='purpleBackupApp.wasabibucket')),
            ],
            options={
                'unique_together': {('bucket', 'batch_number')},
            },
        ),
    ]
