# Generated by Django 5.2.6 on 2025-09-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpleBackupApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebackup',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wasabibucket',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
