# Generated by Django 5.2.6 on 2025-09-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purpleBackupApp', '0002_filebackup_region_wasabibucket_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filebackup',
            name='region',
        ),
        migrations.RemoveField(
            model_name='wasabibucket',
            name='region',
        ),
    ]
