# Generated by Django 5.2.6 on 2025-09-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpleBackupApp', '0003_remove_filebackup_region_remove_wasabibucket_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasabibucket',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
