# Generated by Django 5.2.6 on 2025-09-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purpleBackupApp', '0004_wasabibucket_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasabibucket',
            name='region',
        ),
    ]
